// =============================================================================
// FILE: RootLayout
// =============================================================================
// Wraps every page in the app — shared HTML shell, fonts, and global styles.
// Server Component — runs on the server for all routes.
// Route: app/layout.tsx → applies to all URLs under app/

// =============================================================================
// TOPIC: Metadata and fonts
// =============================================================================
// Study notes:
// - metadata export: sets default <title> and <meta> for all pages (SEO).
// - next/font/google: loads Geist fonts at build time, no layout shift from web fonts.
// - CSS variables (--font-geist-sans) are wired in globals.css via @theme.
//
// Used here: page title, description, and font variables on <html>.

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// =============================================================================
// TOPIC: Root layout and shared page padding
// =============================================================================
// Study notes:
// - layout.tsx wraps {children} — every page renders inside this shell.
// - children: the active page component (e.g. /start, /medium, /start/[name]).
// - px-6 py-8: global horizontal and vertical padding for all pages (DRY — define once).
// - min-h-full flex flex-col: full-height column layout for the app body.
// - Pages no longer need their own px-6 py-8 — see start/[name]/page.tsx (padding removed).
//
// Used here: consistent spacing across the entire app.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col px-6 py-8">{children}</body>
    </html>
  );
}
